# Generated by Django 2.1 on 2018-09-06 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(editable=False)),
                ('value', models.IntegerField(editable=False)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='device.Device')),
            ],
        ),
    ]
