# Generated by Django 3.1.2 on 2020-10-16 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_home_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('ip_address', models.GenericIPAddressField()),
                ('heartbeat', models.DateTimeField(auto_now_add=True)),
                ('is_paired', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.home')),
            ],
        ),
    ]
