# Generated by Django 3.1.3 on 2021-02-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validhume',
            name='id',
        ),
        migrations.AlterField(
            model_name='validhume',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
