# Generated by Django 3.1.2 on 2020-10-16 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_users'),
        ('hume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hume',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.home'),
        ),
    ]
