# Generated by Django 2.1 on 2018-09-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hume',
            name='heartbeat',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
