# Generated by Django 2.2.4 on 2019-08-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hume',
            name='is_dummy',
        ),
        migrations.RemoveField(
            model_name='hume',
            name='token',
        ),
    ]
