# Generated by Django 3.1.2 on 2020-10-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('hume', '0002_auto_20201016_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hume',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
        migrations.CreateModel(
            name='HumeUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
                ('hume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hume.hume')),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user',),
        ),
    ]
