# Generated by Django 3.1.2 on 2020-11-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hume', '0003_auto_20201019_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidHume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('taken', models.BooleanField(default=False)),
            ],
        ),
    ]
