# Generated by Django 3.1.2 on 2020-11-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hume', '0004_validhume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hume',
            name='ip_address',
        ),
    ]
