# Generated by Django 3.1.2 on 2020-11-09 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hume', '0005_remove_hume_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humeuser',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='humeuser',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='humeuser',
            name='hume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hume.hume'),
        ),
    ]
