# Generated by Django 3.1.2 on 2020-11-09 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('home', '0002_home_users'),
        ('hume', '0006_auto_20201109_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hume',
            name='is_paired',
        ),
        migrations.AddField(
            model_name='hume',
            name='hume_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HumeUser',
        ),
    ]
