# Generated by Django 3.1.2 on 2020-11-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hume', '0007_auto_20201109_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hume',
            name='id',
        ),
        migrations.AlterField(
            model_name='hume',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
