# Generated by Django 3.1.2 on 2020-11-09 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hume', '0008_auto_20201109_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hume',
            name='hume_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
