# Generated by Django 3.1.2 on 2020-11-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hume', '0009_auto_20201109_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validhume',
            name='taken',
        ),
    ]
