# Generated by Django 3.1.2 on 2020-11-09 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_users'),
        ('hume', '0010_remove_validhume_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hume',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.home'),
        ),
    ]
