# This compose file composes HINT and all of its dependencies. Including:
#
#  1. The HINT backend, handling both the frontend and HUME APIs. Run by daphne.
#  2. A backing Postgres store for the backend.
#  3. Redis for Django channels.
#  4. A static file server for all things frontend, served by Nginx.
#  5. RabbitMQ for HINT<->HUME communication.
#  6. An Nginx instance to act as a reverse proxy for backend requests.
version: '3.8'

services:

  backend:
    # Change to a different image to run a local build.
    image: ghcr.io/open-home-iot/hint-backend:latest
    environment:
      - BROKER_USER=hint
      - BROKER_PASS=hintpw123
      - BROKER_VHOST=hub
      - BROKER_HOST=rabbitmq
      - BROKER_PORT=5672
      - SECRET_KEY=3jk12hklöe41j2hrkl21jhrilkh12kl12rh###2klrjh12rkl12hjr1kl2jrh12klj12hrkl12hio12ury1i2fh12kdasdas
      - PG_USER=admin
      - PG_PASS=admin
      - PG_HOST=postgres
      - PG_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_SETTINGS_MODULE=backend.settings.prod
    expose:
      - 32000
    depends_on:
      - rabbitmq
      - redis
      - postgres

  ingress:
    # Change to a different image to run a local build.
    image: ghcr.io/open-home-iot/hint-ingress:latest
    ports:
      - '80:80'
    depends_on:
      - backend

  postgres:
    image: postgres:15.0
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=hint
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5
    # Good for local tests when sharing Redis between HUME and HINT.
#    ports:
#      - '6379:6379'
    volumes:
      - redis_volume:/data

  rabbitmq:
    # Change to a different image to run a local build.
    image: ghcr.io/open-home-iot/hint-rabbitmq:latest
    ports:
      - '5672:5672'
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
#      - type: bind
#        source: ../rabbitmq/definitions.json
#        target: /etc/rabbitmq/definitions.json

volumes:
  postgres_volume:
  rabbitmq_volume:
  redis_volume:
