# This compose file is intended for local tests to verify any changes to the
# docker images locally and manually. Useful for deploying a local test cluster
# to try things out in and to check on configuration changes.
version: '3.8'

services:

  backend:
    image: local/hint-backend:latest
    environment:
      - BROKER_USER=hint
      - BROKER_PASS=hintpw123
      - BROKER_VHOST=hub
      - BROKER_HOST=rabbitmq
      - BROKER_PORT=5672
      - SECRET_KEY=3jk12hklöe41j2hrkl21jhrilkh12kl12rh###2klrjh12rkl12hjr1kl2jrh12klj12hrkl12hio12ury1i2fh12kdasdas
      - PG_USER=admin
      - PG_PASS=admin
      - PG_HOST=postgres
      - PG_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_SETTINGS_MODULE=backend.settings.prod
    expose:
      - 32000
    depends_on:
      - rabbitmq
      - redis
      - postgres

  ingress:
    image: local/hint-ingress:latest
    ports:
      - '8080:80'
    depends_on:
      - backend

  postgres:
    image: postgres:15.0
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=hint
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5

  rabbitmq:
    image: local/hint-rabbitmq:latest
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
      - type: bind
        source: ../rabbitmq/definitions.json
        target: /etc/rabbitmq/definitions.json

volumes:
  postgres_volume:
  rabbitmq_volume:
