# Generated by Django 3.2.8 on 2021-12-26 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_remove_device_room'),
        ('home', '0004_auto_20210803_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
