#!/bin/zsh

# BIG NOTE! This script CAN be used to locally build a production-version of HINT, but its main
# purpose is to TEST how to build HINT into production-ready packages in an idempotent way. It
# provides an overview of what is built and in what order, to replicate in CI jobs.

# Build all images locally using this script, then run a local cluster using the "local" compose
# file in the docker directory.

# Testing what commands are needed to build everything for production. MUST BE IDEMPOTENT!
if [ "$#" -ne 1 ]; then
  echo "Provide the ABSOLUTE path to the HINT project root."
  exit 1
fi
HINT_PROJECT_ROOT="$1"
echo "Project root: $HINT_PROJECT_ROOT"
# Workdir is now the hint project root.
cd "$HINT_PROJECT_ROOT" || exit 1

# 1. Build Angular application
# 2. Clear old collected static
# 3. Collect static
# 4. Build ingress/fileserver container image
# 5. Build backend container image
# 6. Build rabbitmq image

#
# LETS GOOOOOO
#

# 1. Build Angular application
cd frontend && ng build --configuration production --output-path="$HINT_PROJECT_ROOT/backend/static/ang"
cd "$HINT_PROJECT_ROOT" || exit 1

# 2. Clear old collected static
rm -rf "$HINT_PROJECT_ROOT/backend/static/collectedstatic"

# 3. Collect static
./manage.py collectstatic

# 4. Build ingress/fileserver container image
docker build . -f docker/ingress.Dockerfile --tag local/hint-ingress:latest

# 5. Build backend container image
docker build . -f docker/backend.Dockerfile --tag local/hint-backend:latest

# 6. Build rabbitmq image
docker build . -f docker/rabbitmq.Dockerfile --tag local/hint-rabbitmq:latest
