#!/bin/bash

cd "$(dirname "$0")"/.. || exit

echo "Linting backend..."
# shellcheck disable=SC2046
flake8 $(find ./backend ! -path "*migrations*" -name "*.py")
cd frontend && ng lint
cd .. && ./manage.py test
