# Generated by Django 2.0.2 on 2018-05-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmhistory',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
