# Generated by Django 2.0.2 on 2018-05-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_auto_20180519_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survconfiguration',
            old_name='alarm',
            new_name='alarm_state',
        ),
    ]
