# Generated by Django 2.1 on 2019-01-12 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0001_initial'),
        ('hume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hume.Hume'),
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
