# Generated by Django 3.1.3 on 2021-02-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicereading',
            name='device',
        ),
        migrations.AlterUniqueTogether(
            name='devicedatasource',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='DeviceAction',
        ),
        migrations.RemoveField(
            model_name='devicedatasource',
            name='data_source_id',
        ),
    ]
