# Generated by Django 2.1 on 2018-09-06 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hume', '0001_initial'),
        ('device', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hume.Hume'),
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='updated_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
