# Generated by Django 2.1 on 2018-09-09 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20180906_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hume.Hume'),
        ),
    ]
