# Generated by Django 2.2.4 on 2019-08-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20190112_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_dummy',
        ),
    ]
