# Generated by Django 3.1.3 on 2021-03-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20210313_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_attached',
        ),
    ]
