# Generated by Django 3.2.4 on 2021-08-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_remove_device_is_attached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedatasource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='devicereading',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
