# Generated by Django 3.2.4 on 2021-08-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20210803_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.IntegerField(choices=[(0, 'Thermometer'), (1, 'Lamp'), (666, 'Custom')]),
        ),
    ]
