# Generated by Django 3.2.8 on 2021-12-26 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_devicestate_devicestategroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='room',
        ),
    ]
