# Generated by Django 4.0 on 2022-01-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_remove_device_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicereading',
            name='data_source',
        ),
        migrations.RenameField(
            model_name='devicestate',
            old_name='device_state_group',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='devicestate',
            old_name='state_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='devicestategroup',
            old_name='group_name',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='DeviceDataSource',
        ),
        migrations.DeleteModel(
            name='DeviceReading',
        ),
    ]
