name: Tinkering

on:
  workflow_dispatch:

jobs:
  tinker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: output stuff
      run: echo $PWD

    # Needed because of imports.
    - name: Create a local settings file
      run: touch backend/settings/local.py

    - name: Collect static files
      run: python manage.py help

    - name: Collect static files
      run: python manage.py collectstatic --help

    - name: Collect static files
      run: python manage.py collectstatic --noinput
